
function test()
{
wynik=0;
if(document.getElementById('css1').checked)
wynik++;
if(document.getElementById('css2').checked)
wynik--;
if(document.getElementById('css3').checked)
wynik--;
if(document.getElementById('css4').checked)
wynik--;
if(document.getElementById('css5').checked)
wynik--;
if(document.getElementById('css6').checked)
wynik++;
if(document.getElementById('lista1').value=="d")
wynik++;
if(document.getElementById('lista1').value=="a")
wynik--;
if(document.getElementById('lista1').value=="b")
wynik--;
if(document.getElementById('lista1').value=="c")
wynik--;
if(document.getElementById('css7').checked)
wynik--;
if(document.getElementById('css8').checked)
wynik++;
if(document.getElementById('css9').checked)
wynik--;
if(document.getElementById('css10').checked)
wynik--;
if(document.getElementById('css11').checked)
wynik++;
if(document.getElementById('css12').checked)
wynik--;
if(document.getElementById('lista2').value=="a")
wynik++;
if(document.getElementById('lista2').value=="b")
wynik--;
if(document.getElementById('lista2').value=="c")
wynik--;
if(document.getElementById('lista2').value=="d")
wynik--;
if(document.getElementById('css13').checked)
wynik--;
if(document.getElementById('css14').checked)
wynik++;
if(document.getElementById('css15').checked)
wynik--;
if(document.getElementById('lista3').value=="a")
wynik--;
if(document.getElementById('lista3').value=="b")
wynik--;
if(document.getElementById('lista3').value=="c")
wynik--;
if(document.getElementById('lista3').value=="d")
wynik++;
if(document.getElementById('css16').checked)
wynik++;
if(document.getElementById('css17').checked)
wynik++;
if(document.getElementById('css18').checked)
wynik--;
if(document.getElementById('css19').checked)
wynik--;
if(document.getElementById('css20').checked)
wynik--;
if(document.getElementById('css21').checked)
wynik++;
if(document.getElementById('css22').checked)
wynik--;
document.getElementById('wynik').innerHTML=wynik;

}
